version: '3.4'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      start_period: 30s
  localgems:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "1337:1337"
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - API_BASE_URL=http://localhost:1337
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - APP_KEYS=aaaaa
      - JWT_SECRET=bbbb
      - API_TOKEN_SALT=cccc
      - ADMIN_JWT_SECRET=dddd
